export default {
  "APIError": "APIError",
  "APIErrors": "APIErrors",
  "APIMeta": "APIMeta",
  "APIMetaAuth": "APIMetaAuth",
  "APIMetaIntegration": "APIMetaIntegration",
  "APIResourceMeta": "APIResourceMeta",
  "PaginationResponse": "PaginationResponse",
  "Workflow": "Workflow",
  "WorkflowApi": "WorkflowApi",
  "WorkflowDeploymentConfig": "WorkflowDeploymentConfig",
  "WorkflowList": "WorkflowList",
  "WorkflowRun": "WorkflowRun",
  "WorkflowRunApi": "WorkflowRunApi",
  "WorkflowRunList": "WorkflowRunList",
  "WorkflowRunStatus": "WorkflowRunStatus",
  "WorkflowRunTriggeredBy": "WorkflowRunTriggeredBy",
  "WorkflowTag": "WorkflowTag",
  "WorkflowTriggerCronRef": "WorkflowTriggerCronRef",
  "WorkflowTriggerEventRef": "WorkflowTriggerEventRef",
  "WorkflowTriggers": "WorkflowTriggers",
  "WorkflowVersion": "WorkflowVersion",
  "WorkflowVersionDefinition": "WorkflowVersionDefinition",
  "WorkflowVersionMeta": "WorkflowVersionMeta"
} 