# coding: utf-8

"""
    Hatchet API

    The Hatchet API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictStr,
    ValidationError,
    field_validator,
)
from typing_extensions import Literal, Self

from hatchet_sdk.clients.rest.models.v1_cel_debug_error_response import (
    V1CELDebugErrorResponse,
)
from hatchet_sdk.clients.rest.models.v1_cel_debug_success_response import (
    V1CELDebugSuccessResponse,
)

V1CELDEBUGRESPONSE_ONE_OF_SCHEMAS = [
    "V1CELDebugErrorResponse",
    "V1CELDebugSuccessResponse",
]


class V1CELDebugResponse(BaseModel):
    """
    V1CELDebugResponse
    """

    # data type: V1CELDebugSuccessResponse
    oneof_schema_1_validator: Optional[V1CELDebugSuccessResponse] = None
    # data type: V1CELDebugErrorResponse
    oneof_schema_2_validator: Optional[V1CELDebugErrorResponse] = None
    actual_instance: Optional[
        Union[V1CELDebugErrorResponse, V1CELDebugSuccessResponse]
    ] = None
    one_of_schemas: Set[str] = {"V1CELDebugErrorResponse", "V1CELDebugSuccessResponse"}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = V1CELDebugResponse.model_construct()
        error_messages = []
        match = 0
        # validate data type: V1CELDebugSuccessResponse
        if not isinstance(v, V1CELDebugSuccessResponse):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `V1CELDebugSuccessResponse`"
            )
        else:
            match += 1
        # validate data type: V1CELDebugErrorResponse
        if not isinstance(v, V1CELDebugErrorResponse):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `V1CELDebugErrorResponse`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in V1CELDebugResponse with oneOf schemas: V1CELDebugErrorResponse, V1CELDebugSuccessResponse. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in V1CELDebugResponse with oneOf schemas: V1CELDebugErrorResponse, V1CELDebugSuccessResponse. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into V1CELDebugSuccessResponse
        try:
            instance.actual_instance = V1CELDebugSuccessResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into V1CELDebugErrorResponse
        try:
            instance.actual_instance = V1CELDebugErrorResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into V1CELDebugResponse with oneOf schemas: V1CELDebugErrorResponse, V1CELDebugSuccessResponse. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into V1CELDebugResponse with oneOf schemas: V1CELDebugErrorResponse, V1CELDebugSuccessResponse. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[Dict[str, Any], V1CELDebugErrorResponse, V1CELDebugSuccessResponse]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
