=begin
#Hatchet API

#The Hatchet API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module HatchetSdkRest
  class WorkerStatus
    ACTIVE = "ACTIVE".freeze
    INACTIVE = "INACTIVE".freeze
    PAUSED = "PAUSED".freeze

    def self.all_vars
      @all_vars ||= [ACTIVE, INACTIVE, PAUSED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WorkerStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WorkerStatus"
    end
  end
end
