// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: streams.sql

package sqlcv1

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStreamTopics = `-- name: CountStreamTopics :one
SELECT COUNT(*) FROM v1_stream_topic WHERE tenant_id = $1::uuid
`

func (q *Queries) CountStreamTopics(ctx context.Context, db DBTX, tenantid uuid.UUID) (int64, error) {
	row := db.QueryRow(ctx, countStreamTopics, tenantid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIdleStreamTopics = `-- name: DeleteIdleStreamTopics :execrows
DELETE FROM v1_stream_topic
WHERE id IN (
    SELECT t.id
    FROM v1_stream_topic t
    LEFT JOIN "TenantResourceLimit" l ON l."tenantId" = t.tenant_id AND l."resource" = 'STREAM_RETENTION'
    WHERE t.last_published_at < NOW() - make_interval(hours => LEAST(COALESCE(l."limitValue", $1::integer), $2::integer))
    ORDER BY t.id
    LIMIT $3::integer
)
`

type DeleteIdleStreamTopicsParams struct {
	Defaultretentionhours int32 `json:"defaultretentionhours"`
	Maxretentionhours     int32 `json:"maxretentionhours"`
	Batchsize             int32 `json:"batchsize"`
}

// Removes topics nobody has published to within their tenant's retention, in
// batches so one sweep never holds a long lock. last_published_at is
// refreshed at least every streamTopicSeenCache TTL while a topic is in use.
func (q *Queries) DeleteIdleStreamTopics(ctx context.Context, db DBTX, arg DeleteIdleStreamTopicsParams) (int64, error) {
	result, err := db.Exec(ctx, deleteIdleStreamTopics, arg.Defaultretentionhours, arg.Maxretentionhours, arg.Batchsize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStreamTopic = `-- name: DeleteStreamTopic :exec
DELETE FROM v1_stream_topic
WHERE id = $1::bigint
`

// Used to roll back UpsertStreamTopic when a newly-created topic turns out to
// violate the tenant's topic-count limit.
func (q *Queries) DeleteStreamTopic(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteStreamTopic, id)
	return err
}

const ensureActiveStreamMessagePartitions = `-- name: EnsureActiveStreamMessagePartitions :exec
SELECT ensure_v1_stream_message_partition(t.tenant_id, NOW() + hours.offset_hours * INTERVAL '1 hour')
FROM (
    SELECT DISTINCT tenant_id
    FROM v1_stream_topic
    WHERE last_published_at > NOW() - INTERVAL '2 hours'
) AS t
CROSS JOIN generate_series(0, 1) AS hours(offset_hours)
`

// Pre-creates this hour's and next hour's partitions for tenants that
// published recently, so their inserts rarely create one inline.
func (q *Queries) EnsureActiveStreamMessagePartitions(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, ensureActiveStreamMessagePartitions)
	return err
}

const ensureStreamMessagePartition = `-- name: EnsureStreamMessagePartition :exec
SELECT
    ensure_v1_stream_message_partition($1::uuid, NOW()),
    ensure_v1_stream_message_partition($1::uuid, NOW() + INTERVAL '1 hour')
`

// Creates the tenant's partitions for this hour and the next, for an insert
// that found none.
func (q *Queries) EnsureStreamMessagePartition(ctx context.Context, db DBTX, tenantid uuid.UUID) error {
	_, err := db.Exec(ctx, ensureStreamMessagePartition, tenantid)
	return err
}

const forceInsertOrderedStreamMessage = `-- name: ForceInsertOrderedStreamMessage :exec
WITH latest AS (
    SELECT last_seq
    FROM v1_stream_producer_cursor
    WHERE tenant_id = $1::uuid AND namespace = $2::text AND topic = $3::text AND producer_id = $5::text
    ORDER BY bucket DESC
    LIMIT 1
), bumped AS (
    INSERT INTO v1_stream_producer_cursor (tenant_id, namespace, topic, producer_id, bucket, last_seq)
    SELECT $1::uuid, $2::text, $3::text, $5::text, (NOW() AT TIME ZONE 'UTC')::date,
        GREATEST(COALESCE(latest.last_seq, -1), $6::bigint)
    FROM (SELECT 1) AS one
    LEFT JOIN latest ON true
    ON CONFLICT (tenant_id, namespace, topic, producer_id, bucket) DO UPDATE
    SET last_seq = GREATEST(v1_stream_producer_cursor.last_seq, EXCLUDED.last_seq), updated_at = NOW()
)
INSERT INTO v1_stream_message (tenant_id, namespace, topic, payload, producer_id, producer_seq)
VALUES ($1::uuid, $2::text, $3::text, $4::bytea, $5::text, $6::bigint)
`

type ForceInsertOrderedStreamMessageParams struct {
	Tenantid    uuid.UUID `json:"tenantid"`
	Namespace   string    `json:"namespace"`
	Topic       string    `json:"topic"`
	Payload     []byte    `json:"payload"`
	Producerid  string    `json:"producerid"`
	Producerseq int64     `json:"producerseq"`
}

// Used only once InsertOrderedStreamMessage has been unable to close a gap
// for too long (see maxProducerGapWait in the streams controller): inserts
// unconditionally and bumps the watermark forward with GREATEST so it never
// regresses, accepting an out-of-order delivery rather than blocking this
// producer's topic forever on a message that never arrived.
func (q *Queries) ForceInsertOrderedStreamMessage(ctx context.Context, db DBTX, arg ForceInsertOrderedStreamMessageParams) error {
	_, err := db.Exec(ctx, forceInsertOrderedStreamMessage,
		arg.Tenantid,
		arg.Namespace,
		arg.Topic,
		arg.Payload,
		arg.Producerid,
		arg.Producerseq,
	)
	return err
}

const getMaxStreamRetentionHours = `-- name: GetMaxStreamRetentionHours :one
SELECT GREATEST(COALESCE(MAX("limitValue"), 0), $1::integer)::integer AS max_hours
FROM "TenantResourceLimit"
WHERE "resource" = 'STREAM_RETENTION'
`

// Shared partitions can only be dropped once every tenant is done with them.
// Tenants without a row use the default.
func (q *Queries) GetMaxStreamRetentionHours(ctx context.Context, db DBTX, defaultretentionhours int32) (int32, error) {
	row := db.QueryRow(ctx, getMaxStreamRetentionHours, defaultretentionhours)
	var max_hours int32
	err := row.Scan(&max_hours)
	return max_hours, err
}

const getStreamMessageRetentionStart = `-- name: GetStreamMessageRetentionStart :one
SELECT MIN(p.hour_start)::timestamptz AS retention_start
FROM list_v1_stream_message_hour_partitions() AS p
WHERE p.tenant_id = $1::uuid
`

// The start of the tenant's oldest hourly partition: its rows inserted before
// it have been dropped. NULL if the tenant has no partitions.
func (q *Queries) GetStreamMessageRetentionStart(ctx context.Context, db DBTX, tenantid uuid.UUID) (pgtype.Timestamptz, error) {
	row := db.QueryRow(ctx, getStreamMessageRetentionStart, tenantid)
	var retention_start pgtype.Timestamptz
	err := row.Scan(&retention_start)
	return retention_start, err
}

const insertOrderedStreamMessage = `-- name: InsertOrderedStreamMessage :one
WITH latest AS (
    SELECT bucket, last_seq, updated_at
    FROM v1_stream_producer_cursor
    WHERE tenant_id = $1::uuid AND namespace = $2::text AND topic = $3::text AND producer_id = $4::text
    ORDER BY bucket DESC
    LIMIT 1
), cas AS (
    UPDATE v1_stream_producer_cursor c
    SET last_seq = $5::bigint, updated_at = NOW()
    FROM latest
    WHERE c.tenant_id = $1::uuid AND c.namespace = $2::text AND c.topic = $3::text AND c.producer_id = $4::text
        AND c.bucket = latest.bucket
        -- computed by the caller as producerSeq - 1 so sqlc binds one plain parameter
        AND c.last_seq = $6::bigint
    RETURNING c.bucket
), first_message AS (
    -- only seq 0 may create a producer's first row, so a reordered seq>0 can't claim it
    INSERT INTO v1_stream_producer_cursor (tenant_id, namespace, topic, producer_id, bucket, last_seq)
    SELECT $1::uuid, $2::text, $3::text, $4::text, (NOW() AT TIME ZONE 'UTC')::date, $5::bigint
    WHERE $5::bigint = 0 AND NOT EXISTS (SELECT 1 FROM latest)
    ON CONFLICT DO NOTHING
    RETURNING 1
), carried_forward AS (
    INSERT INTO v1_stream_producer_cursor (tenant_id, namespace, topic, producer_id, bucket, last_seq)
    SELECT $1::uuid, $2::text, $3::text, $4::text, (NOW() AT TIME ZONE 'UTC')::date, $5::bigint
    FROM cas
    WHERE cas.bucket < (NOW() AT TIME ZONE 'UTC')::date
    ON CONFLICT (tenant_id, namespace, topic, producer_id, bucket) DO UPDATE
    SET last_seq = GREATEST(v1_stream_producer_cursor.last_seq, EXCLUDED.last_seq), updated_at = NOW()
), applied AS (
    SELECT 1 FROM cas
    UNION ALL
    SELECT 1 FROM first_message
), inserted_row AS (
    INSERT INTO v1_stream_message (tenant_id, namespace, topic, payload, producer_id, producer_seq)
    SELECT $1::uuid, $2::text, $3::text, $7::bytea, $4::text, $5::bigint
    WHERE EXISTS (SELECT 1 FROM applied)
    RETURNING 1
)
SELECT
    EXISTS (SELECT 1 FROM inserted_row) AS inserted,
    latest.last_seq AS current_last_seq,
    latest.updated_at AS current_updated_at
FROM (SELECT 1) AS one
LEFT JOIN latest ON true
`

type InsertOrderedStreamMessageParams struct {
	Tenantid        uuid.UUID `json:"tenantid"`
	Namespace       string    `json:"namespace"`
	Topic           string    `json:"topic"`
	Producerid      string    `json:"producerid"`
	Producerseq     int64     `json:"producerseq"`
	Expectedprevseq int64     `json:"expectedprevseq"`
	Payload         []byte    `json:"payload"`
}

type InsertOrderedStreamMessageRow struct {
	Inserted         bool               `json:"inserted"`
	CurrentLastSeq   pgtype.Int8        `json:"current_last_seq"`
	CurrentUpdatedAt pgtype.Timestamptz `json:"current_updated_at"`
}

// Atomically advances the producer's watermark and inserts the message, but
// only if producer_seq is exactly one past the producer's last durably
// applied sequence. The watermark is the producer's row in its latest
// bucket; the compare-and-swap runs against that one row, so concurrent
// attempts serialize on its row lock even across a UTC day boundary. The
// first write of a new day also copies the watermark into today's bucket so
// that an active producer's cursor outlives partition retention.
// inserted=false means this message was NOT applied; current_last_seq (the
// watermark as of this call, NULL if the producer has no row) tells the
// caller whether that's a gap worth retrying (current_last_seq <
// producer_seq - 1) or a stale redelivery (current_last_seq >= producer_seq),
// and current_updated_at when that watermark last advanced.
// a LEFT JOIN rather than a scalar subquery so sqlc infers current_last_seq as nullable
func (q *Queries) InsertOrderedStreamMessage(ctx context.Context, db DBTX, arg InsertOrderedStreamMessageParams) (*InsertOrderedStreamMessageRow, error) {
	row := db.QueryRow(ctx, insertOrderedStreamMessage,
		arg.Tenantid,
		arg.Namespace,
		arg.Topic,
		arg.Producerid,
		arg.Producerseq,
		arg.Expectedprevseq,
		arg.Payload,
	)
	var i InsertOrderedStreamMessageRow
	err := row.Scan(&i.Inserted, &i.CurrentLastSeq, &i.CurrentUpdatedAt)
	return &i, err
}

const listDroppableStreamMessageTenantPartitions = `-- name: ListDroppableStreamMessageTenantPartitions :many
SELECT p.partition_name::text AS partition_name
FROM list_v1_stream_message_empty_tenant_partitions() AS p
WHERE NOT EXISTS (SELECT 1 FROM v1_stream_topic t WHERE t.tenant_id = p.tenant_id)
`

// Tenant partitions with no hourly partitions left and no topics, so nothing
// will write to them again before a new topic re-creates them.
func (q *Queries) ListDroppableStreamMessageTenantPartitions(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.Query(ctx, listDroppableStreamMessageTenantPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var partition_name string
		if err := rows.Scan(&partition_name); err != nil {
			return nil, err
		}
		items = append(items, partition_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamMessageHourPartitions = `-- name: ListStreamMessageHourPartitions :many
SELECT
    p.parent_table::text AS parent_table,
    p.partition_name::text AS partition_name,
    p.tenant_id::uuid AS tenant_id,
    p.hour_start::timestamptz AS hour_start
FROM list_v1_stream_message_hour_partitions() AS p
`

type ListStreamMessageHourPartitionsRow struct {
	ParentTable   string             `json:"parent_table"`
	PartitionName string             `json:"partition_name"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	HourStart     pgtype.Timestamptz `json:"hour_start"`
}

func (q *Queries) ListStreamMessageHourPartitions(ctx context.Context, db DBTX) ([]*ListStreamMessageHourPartitionsRow, error) {
	rows, err := db.Query(ctx, listStreamMessageHourPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStreamMessageHourPartitionsRow
	for rows.Next() {
		var i ListStreamMessageHourPartitionsRow
		if err := rows.Scan(
			&i.ParentTable,
			&i.PartitionName,
			&i.TenantID,
			&i.HourStart,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamMessagesAfterCursor = `-- name: ListStreamMessagesAfterCursor :many
SELECT id, inserted_at, tenant_id, namespace, topic, payload, xact_id, producer_id, producer_seq
FROM v1_stream_message
WHERE tenant_id = $1::uuid
    AND namespace = $2::text
    AND topic = $3::text
    AND id > $4::bigint
    -- the tenant's retention; also prunes partitions outside it
    AND inserted_at >= $5::timestamptz
    AND xact_id < pg_snapshot_xmin(pg_current_snapshot())
ORDER BY id ASC
LIMIT $6::integer
`

type ListStreamMessagesAfterCursorParams struct {
	Tenantid      uuid.UUID          `json:"tenantid"`
	Namespace     string             `json:"namespace"`
	Topic         string             `json:"topic"`
	Afterid       int64              `json:"afterid"`
	Retainedsince pgtype.Timestamptz `json:"retainedsince"`
	Limit         int32              `json:"limit"`
}

// Keyset pagination on id. xact_id < pg_snapshot_xmin(...) excludes rows
// whose inserting transaction may still be in flight, so a concurrent batch
// insert can't let a higher id become visible before a lower one commits.
func (q *Queries) ListStreamMessagesAfterCursor(ctx context.Context, db DBTX, arg ListStreamMessagesAfterCursorParams) ([]*V1StreamMessage, error) {
	rows, err := db.Query(ctx, listStreamMessagesAfterCursor,
		arg.Tenantid,
		arg.Namespace,
		arg.Topic,
		arg.Afterid,
		arg.Retainedsince,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*V1StreamMessage
	for rows.Next() {
		var i V1StreamMessage
		if err := rows.Scan(
			&i.ID,
			&i.InsertedAt,
			&i.TenantID,
			&i.Namespace,
			&i.Topic,
			&i.Payload,
			&i.XactID,
			&i.ProducerID,
			&i.ProducerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamProducerCursorPartitionsBeforeDate = `-- name: ListStreamProducerCursorPartitionsBeforeDate :many
SELECT
    'v1_stream_producer_cursor' AS parent_table,
    p::text AS partition_name
FROM get_v1_partitions_before_date('v1_stream_producer_cursor', $1::date) AS p
`

type ListStreamProducerCursorPartitionsBeforeDateRow struct {
	ParentTable   string `json:"parent_table"`
	PartitionName string `json:"partition_name"`
}

// Kept separate from ListPartitionsBeforeDate because producer cursors are
// retained much longer than the messages they sequence.
func (q *Queries) ListStreamProducerCursorPartitionsBeforeDate(ctx context.Context, db DBTX, date pgtype.Date) ([]*ListStreamProducerCursorPartitionsBeforeDateRow, error) {
	rows, err := db.Query(ctx, listStreamProducerCursorPartitionsBeforeDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStreamProducerCursorPartitionsBeforeDateRow
	for rows.Next() {
		var i ListStreamProducerCursorPartitionsBeforeDateRow
		if err := rows.Scan(&i.ParentTable, &i.PartitionName); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStreamTopic = `-- name: UpsertStreamTopic :one
INSERT INTO v1_stream_topic (tenant_id, namespace, topic)
VALUES ($1::uuid, $2::text, $3::text)
ON CONFLICT (tenant_id, namespace, topic) DO UPDATE
SET last_published_at = NOW()
RETURNING v1_stream_topic.id, v1_stream_topic.tenant_id, v1_stream_topic.namespace, v1_stream_topic.topic, v1_stream_topic.inserted_at, v1_stream_topic.last_published_at, (xmax = 0) AS inserted
`

type UpsertStreamTopicParams struct {
	Tenantid  uuid.UUID `json:"tenantid"`
	Namespace string    `json:"namespace"`
	Topic     string    `json:"topic"`
}

type UpsertStreamTopicRow struct {
	V1StreamTopic V1StreamTopic `json:"v1_stream_topic"`
	Inserted      bool          `json:"inserted"`
}

// Implicitly creates a topic on first publish. The `inserted` column lets the
// caller distinguish a brand-new topic (subject to a per-tenant topic-count
// limit check) from a publish to an already-existing topic.
func (q *Queries) UpsertStreamTopic(ctx context.Context, db DBTX, arg UpsertStreamTopicParams) (*UpsertStreamTopicRow, error) {
	row := db.QueryRow(ctx, upsertStreamTopic, arg.Tenantid, arg.Namespace, arg.Topic)
	var i UpsertStreamTopicRow
	err := row.Scan(
		&i.V1StreamTopic.ID,
		&i.V1StreamTopic.TenantID,
		&i.V1StreamTopic.Namespace,
		&i.V1StreamTopic.Topic,
		&i.V1StreamTopic.InsertedAt,
		&i.V1StreamTopic.LastPublishedAt,
		&i.Inserted,
	)
	return &i, err
}
