// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: streams.sql

package sqlcv1

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStreamTopics = `-- name: CountStreamTopics :one
SELECT COUNT(*) FROM v1_stream_topic WHERE tenant_id = $1::uuid
`

func (q *Queries) CountStreamTopics(ctx context.Context, db DBTX, tenantid uuid.UUID) (int64, error) {
	row := db.QueryRow(ctx, countStreamTopics, tenantid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIdleStreamTopics = `-- name: DeleteIdleStreamTopics :execrows
DELETE FROM v1_stream_topic
WHERE (tenant_id, namespace, topic) IN (
    SELECT t.tenant_id, t.namespace, t.topic
    FROM v1_stream_topic t
    LEFT JOIN "TenantResourceLimit" l ON l."tenantId" = t.tenant_id AND l."resource" = 'STREAM_RETENTION'
    WHERE t.last_published_at < NOW() - make_interval(hours => LEAST(COALESCE(l."limitValue", $1::integer), $2::integer))
    LIMIT $3::integer
)
`

type DeleteIdleStreamTopicsParams struct {
	Defaultretentionhours int32 `json:"defaultretentionhours"`
	Maxretentionhours     int32 `json:"maxretentionhours"`
	Batchsize             int32 `json:"batchsize"`
}

// Removes topics nobody has published to within their tenant's retention, in
// batches so one sweep never holds a long lock. last_published_at is
// refreshed at least every streamTopicSeenCache TTL while a topic is in use.
func (q *Queries) DeleteIdleStreamTopics(ctx context.Context, db DBTX, arg DeleteIdleStreamTopicsParams) (int64, error) {
	result, err := db.Exec(ctx, deleteIdleStreamTopics, arg.Defaultretentionhours, arg.Maxretentionhours, arg.Batchsize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStreamTopic = `-- name: DeleteStreamTopic :exec
DELETE FROM v1_stream_topic
WHERE tenant_id = $1::uuid AND namespace = $2::text AND topic = $3::text
`

type DeleteStreamTopicParams struct {
	Tenantid  uuid.UUID `json:"tenantid"`
	Namespace string    `json:"namespace"`
	Topic     string    `json:"topic"`
}

// Used to roll back UpsertStreamTopic when a newly-created topic turns out to
// violate the tenant's topic-count limit.
func (q *Queries) DeleteStreamTopic(ctx context.Context, db DBTX, arg DeleteStreamTopicParams) error {
	_, err := db.Exec(ctx, deleteStreamTopic, arg.Tenantid, arg.Namespace, arg.Topic)
	return err
}

const ensureActiveStreamMessagePartitions = `-- name: EnsureActiveStreamMessagePartitions :exec
SELECT ensure_v1_stream_message_partition(t.tenant_id, NOW() + hours.offset_hours * INTERVAL '1 hour')
FROM (
    SELECT DISTINCT tenant_id
    FROM v1_stream_topic
    WHERE last_published_at > NOW() - INTERVAL '2 hours'
) AS t
CROSS JOIN generate_series(0, 1) AS hours(offset_hours)
`

// Pre-creates this hour's and next hour's partitions for tenants that
// published recently, so their inserts rarely create one inline.
func (q *Queries) EnsureActiveStreamMessagePartitions(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, ensureActiveStreamMessagePartitions)
	return err
}

const ensureStreamMessagePartition = `-- name: EnsureStreamMessagePartition :exec
SELECT
    ensure_v1_stream_message_partition($1::uuid, NOW()),
    ensure_v1_stream_message_partition($1::uuid, NOW() + INTERVAL '1 hour')
`

// Creates the tenant's partitions for this hour and the next, for an insert
// that found none.
func (q *Queries) EnsureStreamMessagePartition(ctx context.Context, db DBTX, tenantid uuid.UUID) error {
	_, err := db.Exec(ctx, ensureStreamMessagePartition, tenantid)
	return err
}

const getStreamMessageRetentionStart = `-- name: GetStreamMessageRetentionStart :one
SELECT get_v1_stream_message_retention_start($1::uuid)::timestamptz AS retention_start
`

// The start of the tenant's oldest hourly partition: its rows inserted before
// it have been dropped. NULL if the tenant has no partitions.
func (q *Queries) GetStreamMessageRetentionStart(ctx context.Context, db DBTX, tenantid uuid.UUID) (pgtype.Timestamptz, error) {
	row := db.QueryRow(ctx, getStreamMessageRetentionStart, tenantid)
	var retention_start pgtype.Timestamptz
	err := row.Scan(&retention_start)
	return retention_start, err
}

const listDroppableStreamMessageTenantPartitions = `-- name: ListDroppableStreamMessageTenantPartitions :many
SELECT p.partition_name::text AS partition_name
FROM list_v1_stream_message_empty_tenant_partitions() AS p
WHERE NOT EXISTS (SELECT 1 FROM v1_stream_topic t WHERE t.tenant_id = p.tenant_id)
`

// Tenant partitions with no hourly partitions left and no topics, so nothing
// will write to them again before a new topic re-creates them.
func (q *Queries) ListDroppableStreamMessageTenantPartitions(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.Query(ctx, listDroppableStreamMessageTenantPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var partition_name string
		if err := rows.Scan(&partition_name); err != nil {
			return nil, err
		}
		items = append(items, partition_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamMessageHourPartitions = `-- name: ListStreamMessageHourPartitions :many
SELECT
    p.parent_table::text AS parent_table,
    p.partition_name::text AS partition_name,
    p.tenant_id::uuid AS tenant_id,
    p.hour_start::timestamptz AS hour_start
FROM list_v1_stream_message_hour_partitions() AS p
`

type ListStreamMessageHourPartitionsRow struct {
	ParentTable   string             `json:"parent_table"`
	PartitionName string             `json:"partition_name"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	HourStart     pgtype.Timestamptz `json:"hour_start"`
}

func (q *Queries) ListStreamMessageHourPartitions(ctx context.Context, db DBTX) ([]*ListStreamMessageHourPartitionsRow, error) {
	rows, err := db.Query(ctx, listStreamMessageHourPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStreamMessageHourPartitionsRow
	for rows.Next() {
		var i ListStreamMessageHourPartitionsRow
		if err := rows.Scan(
			&i.ParentTable,
			&i.PartitionName,
			&i.TenantID,
			&i.HourStart,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamMessagesAfterCursor = `-- name: ListStreamMessagesAfterCursor :many
SELECT id, inserted_at, tenant_id, namespace, topic, payload, producer_id, producer_seq
FROM (
    SELECT page.id, page.inserted_at, page.tenant_id, page.namespace, page.topic, page.payload, page.producer_id, page.producer_seq, SUM(octet_length(page.payload)) OVER (ORDER BY page.id) - octet_length(page.payload) AS bytes_before
    FROM (
        SELECT id, inserted_at, tenant_id, namespace, topic, payload, producer_id, producer_seq
        FROM v1_stream_message
        WHERE tenant_id = $1::uuid
            AND namespace = $2::text
            AND topic = $3::text
            AND id > $4::bigint
            -- the tenant's retention; also prunes partitions outside it
            AND inserted_at >= $5::timestamptz
        ORDER BY id ASC
        LIMIT $6::integer
    ) AS page
) AS sized
WHERE bytes_before < $7::bigint
ORDER BY id ASC
`

type ListStreamMessagesAfterCursorParams struct {
	Tenantid      uuid.UUID          `json:"tenantid"`
	Namespace     string             `json:"namespace"`
	Topic         string             `json:"topic"`
	Afterid       int64              `json:"afterid"`
	Retainedsince pgtype.Timestamptz `json:"retainedsince"`
	Limit         int32              `json:"limit"`
	Maxbytes      int64              `json:"maxbytes"`
}

// Keyset pagination on id, a topic's offset: offsets become visible strictly
// in order (see ReserveStreamTopicOffsets), so nothing after the cursor can
// appear later behind it. A page also stops once its payloads reach @maxBytes (always keeping its
// first row). Payloads over ~2KB are stored out of line, and octet_length
// reads their size without fetching them, so only the rows returned have
// their payloads loaded.
func (q *Queries) ListStreamMessagesAfterCursor(ctx context.Context, db DBTX, arg ListStreamMessagesAfterCursorParams) ([]*V1StreamMessage, error) {
	rows, err := db.Query(ctx, listStreamMessagesAfterCursor,
		arg.Tenantid,
		arg.Namespace,
		arg.Topic,
		arg.Afterid,
		arg.Retainedsince,
		arg.Limit,
		arg.Maxbytes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*V1StreamMessage
	for rows.Next() {
		var i V1StreamMessage
		if err := rows.Scan(
			&i.ID,
			&i.InsertedAt,
			&i.TenantID,
			&i.Namespace,
			&i.Topic,
			&i.Payload,
			&i.ProducerID,
			&i.ProducerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamProducerCursorPartitionsBeforeDate = `-- name: ListStreamProducerCursorPartitionsBeforeDate :many
SELECT
    'v1_stream_producer_cursor' AS parent_table,
    p::text AS partition_name
FROM get_v1_partitions_before_date('v1_stream_producer_cursor', $1::date) AS p
`

type ListStreamProducerCursorPartitionsBeforeDateRow struct {
	ParentTable   string `json:"parent_table"`
	PartitionName string `json:"partition_name"`
}

// Kept separate from ListPartitionsBeforeDate because producer cursors have
// their own retention.
func (q *Queries) ListStreamProducerCursorPartitionsBeforeDate(ctx context.Context, db DBTX, date pgtype.Date) ([]*ListStreamProducerCursorPartitionsBeforeDateRow, error) {
	rows, err := db.Query(ctx, listStreamProducerCursorPartitionsBeforeDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStreamProducerCursorPartitionsBeforeDateRow
	for rows.Next() {
		var i ListStreamProducerCursorPartitionsBeforeDateRow
		if err := rows.Scan(&i.ParentTable, &i.PartitionName); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStreamTopic = `-- name: UpsertStreamTopic :one
INSERT INTO v1_stream_topic (tenant_id, namespace, topic)
VALUES ($1::uuid, $2::text, $3::text)
ON CONFLICT (tenant_id, namespace, topic) DO UPDATE
SET last_published_at = NOW()
RETURNING v1_stream_topic.tenant_id, v1_stream_topic.namespace, v1_stream_topic.topic, v1_stream_topic.inserted_at, v1_stream_topic.last_published_at, v1_stream_topic.last_offset, (xmax = 0) AS inserted
`

type UpsertStreamTopicParams struct {
	Tenantid  uuid.UUID `json:"tenantid"`
	Namespace string    `json:"namespace"`
	Topic     string    `json:"topic"`
}

type UpsertStreamTopicRow struct {
	V1StreamTopic V1StreamTopic `json:"v1_stream_topic"`
	Inserted      bool          `json:"inserted"`
}

// Implicitly creates a topic on first publish. The `inserted` column lets the
// caller distinguish a brand-new topic (subject to a per-tenant topic-count
// limit check) from a publish to an already-existing topic.
func (q *Queries) UpsertStreamTopic(ctx context.Context, db DBTX, arg UpsertStreamTopicParams) (*UpsertStreamTopicRow, error) {
	row := db.QueryRow(ctx, upsertStreamTopic, arg.Tenantid, arg.Namespace, arg.Topic)
	var i UpsertStreamTopicRow
	err := row.Scan(
		&i.V1StreamTopic.TenantID,
		&i.V1StreamTopic.Namespace,
		&i.V1StreamTopic.Topic,
		&i.V1StreamTopic.InsertedAt,
		&i.V1StreamTopic.LastPublishedAt,
		&i.V1StreamTopic.LastOffset,
		&i.Inserted,
	)
	return &i, err
}
