global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hatchet-metrics'
    static_configs:
      - targets: ['host.docker.internal:7007']  # Assuming Hatchet API runs on port 8080
    metrics_path: '/metrics'
    scrape_interval: 10s
