#!/bin/bash

set -eux

# Match `start-api.sh`/`start-lite.sh`: start Caddy so `https://app.dev.hatchet-tools.com` works
# when running *only* the frontend task.
if command -v caddy >/dev/null 2>&1; then
  # `caddy start` exits non-zero if it's already running; don't fail the dev task for that.
  caddy start || true
fi

# If a developer is using the local Caddy reverse-proxy (`Caddyfile`) then the browser origin will be
# `https://app.dev.hatchet-tools.com` (port 443) while Vite still runs on port 5173. Without telling
# Vite about the *public* HMR socket (wss://...:443), hot reload won't work when accessing via Caddy.
#
# We infer this from the repo root `.env` (generated by `task set-env-all` / `task setup`) which sets
# `SERVER_AUTH_COOKIE_DOMAIN=app.dev.hatchet-tools.com` in the standard dev flow.
if [ -f ./.env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a

  if [ "${SERVER_AUTH_COOKIE_DOMAIN:-}" = "app.dev.hatchet-tools.com" ]; then
    export VITE_HMR_PROTOCOL="${VITE_HMR_PROTOCOL:-wss}"
    export VITE_HMR_HOST="${VITE_HMR_HOST:-app.dev.hatchet-tools.com}"
    export VITE_HMR_CLIENT_PORT="${VITE_HMR_CLIENT_PORT:-443}"
  fi
fi

if [ "${SERVER_AUTH_COOKIE_DOMAIN:-}" = "app.dev.hatchet-tools.com" ]; then
  echo "Open: https://app.dev.hatchet-tools.com (Caddy -> Vite)"
else
  echo "Open: http://localhost:5173 (direct Vite)"
fi

cd ./frontend/app && pnpm run dev
