run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - gofmt
    - unused
    - gosimple
    - exportloopref
    - gocritic
    - gosec
    - errcheck
    - goimports
    - revive
    - staticcheck
    - vet
    - stylecheck
    - unconvert
    - ineffassign

linters-settings:
  goimports:
    local-prefixes: github.com/hatchet-dev/hatchet
  staticcheck:
    checks:
      - all
      - "-ST1003"
      - "-SA4006"
      - "-SA1029"
  stylecheck:
    checks:
      - all
      - "-ST1003"
      - "-SA4006"
      - "-ST1016"
      - "-ST1005"

issues:
  exclude-files:
    - "pkg/repository/prisma/db/db_gen.go"
  exclude:
    - "by other packages, and that stutters; consider calling this"
    - "var-naming:"
    - "receiver-naming:"
    - "unexported-return:"
    - "unused-parameter: parameter"
    - "context-keys-type: should not use basic type string"
    - "error strings should not be capitalized"
