run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - gofmt
    - unused
    - gosimple
    - exportloopref
    - gocritic
    - gosec
    - errcheck
    - goimports
    - revive
    - staticcheck
    - vet
    - stylecheck
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/hatchet-dev/hatchet
