run:
  timeout: 5m
linters:
  enable:
    - gofmt
    - revive
    - exportloopref
    - gocritic
    - gosec
    - errcheck
    - goimports
    - revive
    - staticcheck
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/hatchet-dev/hatchet
