version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    staticcheck:
      checks:
        - -SA1029
        - -SA4006
        - -ST1003
        - -ST1005
        - -ST1016
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: by other packages, and that stutters; consider calling this
      - path: (.+)\.go$
        text: "var-naming:"
      - path: (.+)\.go$
        text: "receiver-naming:"
      - path: (.+)\.go$
        text: "unexported-return:"
      - path: (.+)\.go$
        text: "unused-parameter: parameter"
      - path: (.+)\.go$
        text: "context-keys-type: should not use basic type string"
      - path: (.+)\.go$
        text: error strings should not be capitalized
      - linters:
          - staticcheck
        text: "ST1003:"

    paths:
      - third_party$
      - builtin$
      - examples$
      - '(.+)_test\.go'
      - "cmd/hatchet-loadtest/rampup/(.+).go"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hatchet-dev/hatchet
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
