repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        exclude: ^examples/
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^examples/
      - id: end-of-file-fixer
        exclude: ^examples/
      - id: trailing-whitespace
        exclude: ^examples/
      - id: check-yaml
        exclude: (^examples/|^cmd/hatchet-cli/cli/templates/)
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.8.0
    hooks:
      - id: golangci-lint
        args: ["--config=.golangci.yml", "--allow-parallel-runners"]
        exclude: ^(examples/|sdks/guides/go/|sdks/go/examples/)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: ^sdks/python/
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black
        files: ^sdks/python/
  - repo: local
    hooks:
      - id: mypy
        name: mypy (poetry)
        entry: bash -c 'cd sdks/python && poetry run mypy . --config-file=pyproject.toml'
        language: system
        types: [python]
