services:
  prometheus:
    image: prom/prometheus:latest
    container_name: hatchet-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./hack/dev/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./hack/dev/prometheus.web-config.yml:/etc/prometheus/web-config.yml
      - hatchet_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.config.file=/etc/prometheus/web-config.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: hatchet-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - hatchet_grafana_data:/var/lib/grafana
      - ./hack/dev/grafana/provisioning:/etc/grafana/provisioning
      - ./hack/dev/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  hyperdx:
    image: docker.hyperdx.io/hyperdx/hyperdx-all-in-one:latest
    container_name: hatchet-hyperdx
    ports:
      - "8081:8080" # HyperDX UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - hatchet_hyperdx_data:/data/db
      - hatchet_hyperdx_data:/var/lib/clickhouse
      - hatchet_hyperdx_data:/var/log/clickhouse-server

volumes:
  hatchet_prometheus_data:
  hatchet_grafana_data:
  hatchet_hyperdx_data:
