version: "3"

tasks:
  set-etc-hosts:
    cmds:
      - sudo sh ./hack/dev/manage-hosts.sh add 127.0.0.1 app.dev.hatchet-tools.com
  prisma-migrate:
    cmds:
      - sh ./hack/dev/run-go-with-env.sh run github.com/steebchen/prisma-client-go migrate dev
  seed-dev:
    cmds:
      - sh ./hack/dev/run-npx-with-env.sh prisma db push --force-reset --skip-generate
      - SEED_DEVELOPMENT=true sh ./hack/dev/run-go-with-env.sh run ./cmd/hatchet-admin seed
  start-dev:
    deps:
      - task: start-api
      - task: start-engine
      - task: start-frontend
  start-api:
    cmds:
      - sh ./hack/dev/start-api.sh
  start-engine:
    cmds:
      - sh ./hack/dev/start-engine.sh
  start-frontend:
    cmds:
      - sh ./hack/dev/start-frontend.sh
  generate:
    cmds:
      - task: deps
      - task: generate-api
      - task: generate-go
      - task: generate-proto
      - task: generate-sqlc
  deps:
    cmds:
      - go mod download
      - cd frontend/app/ && pnpm install
      - cd frontend/docs/ && pnpm install
  generate-api:
    cmds:
      - task: generate-api-server
      - task: generate-api-client
  generate-certs:
    cmds:
      - sh ./hack/dev/generate-x509-certs.sh ./hack/dev/certs
  generate-local-encryption-keys:
    cmds:
      - sh ./hack/dev/generate-local-encryption-keys.sh ./hack/dev/encryption-keys
  generate-dev-api-token:
    cmds:
      - sh ./hack/dev/generate-dev-api-token.sh
  generate-api-server:
    cmds:
      - sh ./hack/oas/generate-server.sh
    silent: true
  generate-api-client:
    cmds:
      - sh ./hack/oas/generate-client.sh
    silent: true
  generate-go:
    cmds:
      - go generate ./...
  generate-proto:
    cmds:
      - sh ./hack/proto/proto.sh
  generate-proto-python:
    dir: ./python-client
    cmds:
      - sh ./generate.sh
  generate-sqlc:
    cmds:
      - npx --yes prisma migrate diff --from-empty --to-schema-datasource prisma/schema.prisma --script > internal/repository/prisma/dbsqlc/schema.sql
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.24.0 generate --file internal/repository/prisma/dbsqlc/sqlc.yaml
  kill-query-engines:
    cmds:
      - ps -A | grep 'prisma-query-engine-darwin-arm64' | grep -v grep | awk '{print $1}' | xargs kill -9 $1
  prisma-studio:
    cmds:
      - sh ./hack/dev/run-npx-with-env.sh prisma studio
