package loaderutils

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/tink-crypto/tink-go/aead"
	"github.com/tink-crypto/tink-go/insecurecleartextkeyset"
	"github.com/tink-crypto/tink-go/jwt"
	"github.com/tink-crypto/tink-go/keyset"
)

type TokenConf struct {
	ExpiresAt            time.Time
	ServerURL            string
	GrpcBroadcastAddress string
	TenantId             string
}

// ErrInvalidToken is returned when the JWT token is invalid or cannot be verified.
var ErrInvalidToken = fmt.Errorf("invalid token: signature verification failed")

// ErrMissingPublicKey is returned when the public keyset is not configured.
var ErrMissingPublicKey = fmt.Errorf("JWT public keyset is required for token verification")

// ErrTokenExpired is returned when the JWT token has expired.
var ErrTokenExpired = fmt.Errorf("token has expired")

// ErrMissingClaim is returned when a required claim is missing from the JWT.
type ErrMissingClaim struct {
	ClaimName string
}

func (e *ErrMissingClaim) Error() string {
	return fmt.Sprintf("%s claim not found", e.ClaimName)
}

// GetConfFromJWT extracts configuration from a JWT token after verifying its signature.
// The publicKeyset should be a base64-encoded public JWT keyset. If the keyset is
// encrypted (as generated by the Hatchet server), the masterKeyset must also be provided.
// If the keyset is in raw (insecure) format, the masterKeyset can be empty.
func GetConfFromJWT(token string, publicKeyset string, masterKeyset string) (*TokenConf, error) {
	claims, err := ExtractAndVerifyClaims(token, publicKeyset, masterKeyset)
	if err != nil {
		return nil, err
	}

	serverURL, ok := claims["server_url"].(string)
	if !ok {
		return nil, &ErrMissingClaim{ClaimName: "server_url"}
	}

	grpcBroadcastAddress, ok := claims["grpc_broadcast_address"].(string)
	if !ok {
		return nil, &ErrMissingClaim{ClaimName: "grpc_broadcast_address"}
	}

	expiresAtFloat, ok := claims["exp"].(float64)
	if !ok {
		return nil, &ErrMissingClaim{ClaimName: "exp"}
	}

	expiresAt := time.Unix(int64(expiresAtFloat), 0)

	if expiresAt.Before(time.Now()) {
		return nil, ErrTokenExpired
	}

	tenantId, ok := claims["sub"].(string)
	if !ok {
		return nil, &ErrMissingClaim{ClaimName: "sub"}
	}

	return &TokenConf{
		ExpiresAt:            expiresAt,
		ServerURL:            serverURL,
		GrpcBroadcastAddress: grpcBroadcastAddress,
		TenantId:             tenantId,
	}, nil
}

// ExtractAndVerifyClaims verifies the JWT signature and extracts claims from the token.
// The publicKeyset should be a base64-encoded public JWT keyset. If the keyset is
// encrypted (as generated by the Hatchet server), the masterKeyset must also be provided.
// If the keyset is in raw (insecure) format, the masterKeyset can be empty.
func ExtractAndVerifyClaims(token string, publicKeyset string, masterKeyset string) (map[string]interface{}, error) {
	if publicKeyset == "" {
		return nil, ErrMissingPublicKey
	}

	verifier, err := newJWTVerifier(publicKeyset, masterKeyset)
	if err != nil {
		return nil, fmt.Errorf("failed to create JWT verifier: %w", err)
	}

	// Create a validator that does NOT check expiration - we handle that separately
	validator, err := jwt.NewValidator(&jwt.ValidatorOpts{})
	if err != nil {
		return nil, fmt.Errorf("failed to create JWT validator: %w", err)
	}

	verifiedJwt, err := verifier.VerifyAndDecode(token, validator)
	if err != nil {
		return nil, ErrInvalidToken
	}

	claims := make(map[string]interface{})

	if verifiedJwt.HasStringClaim("server_url") {
		if serverURL, err := verifiedJwt.StringClaim("server_url"); err == nil {
			claims["server_url"] = serverURL
		}
	}

	if verifiedJwt.HasStringClaim("grpc_broadcast_address") {
		if grpcAddr, err := verifiedJwt.StringClaim("grpc_broadcast_address"); err == nil {
			claims["grpc_broadcast_address"] = grpcAddr
		}
	}

	if verifiedJwt.HasSubject() {
		if subject, err := verifiedJwt.Subject(); err == nil {
			claims["sub"] = subject
		}
	}

	if verifiedJwt.HasExpiration() {
		// Manually extract the exp claim from the JWT payload since VerifiedJWT doesn't expose it
		// Parse the second part (payload) of the JWT
		parts := strings.Split(token, ".")
		if len(parts) == 3 {
			payloadBytes, err := base64.RawURLEncoding.DecodeString(parts[1])
			if err == nil {
				var payload map[string]interface{}
				if err := json.Unmarshal(payloadBytes, &payload); err == nil {
					if exp, ok := payload["exp"].(float64); ok {
						claims["exp"] = exp
					}
				}
			}
		}
	}

	return claims, nil
}

// newJWTVerifier creates a JWT verifier from a base64-encoded keyset.
// If masterKeyset is provided, it decrypts the encrypted keyset first.
// If masterKeyset is empty, it reads the keyset as insecure/raw format.
func newJWTVerifier(publicKeyset string, masterKeyset string) (jwt.Verifier, error) {
	keysetBytes, err := decodeBase64(publicKeyset)
	if err != nil {
		return nil, fmt.Errorf("failed to decode keyset: %w", err)
	}

	var handle *keyset.Handle

	if masterKeyset != "" {
		handle, err = readEncryptedKeyset(keysetBytes, masterKeyset)
		if err != nil {
			return nil, fmt.Errorf("failed to read encrypted keyset: %w", err)
		}
	} else {
		handle, err = readInsecureKeyset(keysetBytes)
		if err != nil {
			return nil, fmt.Errorf("failed to read insecure keyset: %w", err)
		}
	}

	verifier, err := jwt.NewVerifier(handle)
	if err != nil {
		return nil, fmt.Errorf("failed to create verifier: %w", err)
	}

	return verifier, nil
}

// readEncryptedKeyset reads an encrypted keyset using the provided master key.
func readEncryptedKeyset(keysetBytes []byte, masterKeyset string) (*keyset.Handle, error) {
	masterKeyBytes, err := decodeBase64(masterKeyset)
	if err != nil {
		return nil, fmt.Errorf("failed to decode master keyset: %w", err)
	}

	masterHandle, err := insecurecleartextkeyset.Read(keyset.NewJSONReader(bytes.NewReader(masterKeyBytes)))
	if err != nil {
		return nil, fmt.Errorf("failed to read master key handle: %w", err)
	}

	a, err := aead.New(masterHandle)
	if err != nil {
		return nil, fmt.Errorf("failed to create AEAD from master key: %w", err)
	}

	handle, err := keyset.Read(keyset.NewJSONReader(bytes.NewReader(keysetBytes)), a)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt and read keyset: %w", err)
	}

	return handle, nil
}

// readInsecureKeyset reads a raw (unencrypted) keyset.
func readInsecureKeyset(keysetBytes []byte) (*keyset.Handle, error) {
	handle, err := insecurecleartextkeyset.Read(keyset.NewJSONReader(bytes.NewReader(keysetBytes)))
	if err != nil {
		return nil, fmt.Errorf("failed to read insecure keyset: %w", err)
	}
	return handle, nil
}

// decodeBase64 decodes a base64-encoded string, supporting raw std encoding.
func decodeBase64(s string) ([]byte, error) {
	decoded := make([]byte, base64.RawStdEncoding.DecodedLen(len(s)))
	n, err := base64.RawStdEncoding.Decode(decoded, []byte(s))
	if err != nil {
		return nil, fmt.Errorf("failed to decode base64: %w", err)
	}
	return decoded[:n], nil
}

// GetClientJWTConfig retrieves the JWT public keyset and master keyset from environment variables.
// These values should be set from HATCHET_CLIENT_ENCRYPTION_JWT_PUBLIC_KEYSET and
// HATCHET_CLIENT_ENCRYPTION_MASTER_KEYSET respectively.
func GetClientJWTConfig() (publicKeyset string, masterKeyset string) {
	publicKeyset = os.Getenv("HATCHET_CLIENT_ENCRYPTION_JWT_PUBLIC_KEYSET")
	masterKeyset = os.Getenv("HATCHET_CLIENT_ENCRYPTION_MASTER_KEYSET")
	return
}
