name: "test-job-timeout"
version: v0.1.0
triggers:
  events:
    - user:create
jobs:
  timeout-job:
    timeout: 3s
    steps:
      - id: timeout
        action: timeout:timeout
        timeout: 10s
