module Hatchet
  module ConcurrencyLimitStrategy
    CANCEL_IN_PROGRESS: Symbol
    CANCEL_NEWEST: Symbol
    GROUP_ROUND_ROBIN: Symbol
    QUEUE: Symbol
    CANCEL_QUEUED_EXCEPT_NEWEST: Symbol
    CANCEL_QUEUED_EXCEPT_OLDEST: Symbol
  end

  module ConcurrencyProto
    LIMIT_STRATEGY_MAP: Hash[Symbol, Symbol]

    def self.split_max_runs: (Integer | String max_runs) -> [Integer, String?]
  end

  class ConcurrencyExpression
    LIMIT_STRATEGY_MAP: Hash[Symbol, Symbol]

    attr_reader expression: String
    attr_reader max_runs: Integer | String
    attr_reader limit_strategy: Symbol

    def initialize: (expression: String, ?max_runs: Integer | String, ?limit_strategy: Symbol) -> void
    def to_h: () -> Hash[Symbol, untyped]
    def to_proto: () -> untyped
  end

  class SharedConcurrency
    attr_reader name: String
    attr_reader expression: String
    attr_reader max_runs: Integer | String
    attr_reader limit_strategy: Symbol

    def initialize: (name: String, expression: String, ?max_runs: Integer | String, ?limit_strategy: Symbol) -> void
    def to_h: () -> Hash[Symbol, untyped]
    def to_proto: () -> untyped
  end
end
