module Hatchet
  class NonRetryableError < Error
    def initialize: (?String message) -> void
  end

  class ResourceExhaustedError < Error
    def initialize: (?String message) -> void
  end

  class DedupeViolationError < Error
    def initialize: (?String message) -> void
  end

  class TaskRunError < Error
    attr_reader task_run_external_id: String?
    attr_reader exc: String

    def initialize: (String message, ?task_run_external_id: String?) -> void
  end

  class FailedRunError < Error
    attr_reader exceptions: Array[TaskRunError]

    def initialize: (Array[TaskRunError] exceptions) -> void
  end
end
