#!/usr/bin/env bash
#
# Generates the protobuf-es bindings for the protos the SDK calls into src/protoc-es: message
# schemas and the Connect service descriptors that @connectrpc/connect clients are created from
# (protoc-gen-es v2 emits both; there is no separate connect plugin for Connect v2).
#
# The ts-proto bindings in src/protoc are generated by generate-protoc.sh from the same protos
# and are still the SDK's public message types; the two outputs coexist while the clients move
# to the Connect transport. Run from this directory (pnpm run generate-protoc-es), or through
# `task generate-proto-typescript-es` from the repository root. Needs protoc on PATH (or PROTOC).
#
# v1/operator.proto is the engine-internal OperatorService API and v1/serverless.proto the
# serverless operator's wire contract; neither is called by this package.

set -euo pipefail

cd "$(dirname "$0")"

OUT_DIR="./src/protoc-es"
IN_DIR="../../api-contracts"
VENDOR_DIR="../../hack/proto/vendor"
PROTOC="${PROTOC:-protoc}"

PROTOS=()
while IFS= read -r f; do
  case "$f" in
    v1/operator.proto | v1/serverless.proto) continue ;;
  esac
  PROTOS+=("$f")
done < <(cd "$IN_DIR" && find . -name '*.proto' | sed 's#^\./##' | sort)

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

"$PROTOC" \
  --plugin=protoc-gen-es=./node_modules/.bin/protoc-gen-es \
  --es_out="$OUT_DIR" \
  --es_opt=target=ts \
  --proto_path="$IN_DIR" \
  --proto_path="$VENDOR_DIR" \
  "${PROTOS[@]}" \
  google/rpc/status.proto
