// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.19.1
// source: v1/dispatcher.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { type CallContext, type CallOptions } from 'nice-grpc-common';
import { DurableEventListenerConditions } from './shared/condition';

export const protobufPackage = 'v1';

export interface RegisterDurableEventRequest {
  /** external uuid for the task run */
  taskId: string;
  /** external uuid for the workflow run */
  workflowRunId: string;
  /** (optional) the task conditions for creating the task */
  conditions: DurableEventListenerConditions | undefined;
}

export interface RegisterDurableEventResponse {
  matchId: number;
}

export interface ListenForDurableEventRequest {
  /** single listener per worker */
  taskId: string;
  /** the match id for the listener */
  matchId: number;
}

export interface DurableEvent {
  taskId: string;
  matchId: number;
  /** the data for the event */
  data: Uint8Array;
}

function createBaseRegisterDurableEventRequest(): RegisterDurableEventRequest {
  return { taskId: '', workflowRunId: '', conditions: undefined };
}

export const RegisterDurableEventRequest: MessageFns<RegisterDurableEventRequest> = {
  encode(
    message: RegisterDurableEventRequest,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.taskId !== '') {
      writer.uint32(10).string(message.taskId);
    }
    if (message.workflowRunId !== '') {
      writer.uint32(18).string(message.workflowRunId);
    }
    if (message.conditions !== undefined) {
      DurableEventListenerConditions.encode(message.conditions, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterDurableEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterDurableEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workflowRunId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.conditions = DurableEventListenerConditions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterDurableEventRequest {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : '',
      workflowRunId: isSet(object.workflowRunId) ? globalThis.String(object.workflowRunId) : '',
      conditions: isSet(object.conditions)
        ? DurableEventListenerConditions.fromJSON(object.conditions)
        : undefined,
    };
  },

  toJSON(message: RegisterDurableEventRequest): unknown {
    const obj: any = {};
    if (message.taskId !== '') {
      obj.taskId = message.taskId;
    }
    if (message.workflowRunId !== '') {
      obj.workflowRunId = message.workflowRunId;
    }
    if (message.conditions !== undefined) {
      obj.conditions = DurableEventListenerConditions.toJSON(message.conditions);
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterDurableEventRequest>): RegisterDurableEventRequest {
    return RegisterDurableEventRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterDurableEventRequest>): RegisterDurableEventRequest {
    const message = createBaseRegisterDurableEventRequest();
    message.taskId = object.taskId ?? '';
    message.workflowRunId = object.workflowRunId ?? '';
    message.conditions =
      object.conditions !== undefined && object.conditions !== null
        ? DurableEventListenerConditions.fromPartial(object.conditions)
        : undefined;
    return message;
  },
};

function createBaseRegisterDurableEventResponse(): RegisterDurableEventResponse {
  return { matchId: 0 };
}

export const RegisterDurableEventResponse: MessageFns<RegisterDurableEventResponse> = {
  encode(
    message: RegisterDurableEventResponse,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.matchId !== 0) {
      writer.uint32(8).int64(message.matchId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterDurableEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterDurableEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.matchId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterDurableEventResponse {
    return { matchId: isSet(object.matchId) ? globalThis.Number(object.matchId) : 0 };
  },

  toJSON(message: RegisterDurableEventResponse): unknown {
    const obj: any = {};
    if (message.matchId !== 0) {
      obj.matchId = Math.round(message.matchId);
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterDurableEventResponse>): RegisterDurableEventResponse {
    return RegisterDurableEventResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterDurableEventResponse>): RegisterDurableEventResponse {
    const message = createBaseRegisterDurableEventResponse();
    message.matchId = object.matchId ?? 0;
    return message;
  },
};

function createBaseListenForDurableEventRequest(): ListenForDurableEventRequest {
  return { taskId: '', matchId: 0 };
}

export const ListenForDurableEventRequest: MessageFns<ListenForDurableEventRequest> = {
  encode(
    message: ListenForDurableEventRequest,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.taskId !== '') {
      writer.uint32(10).string(message.taskId);
    }
    if (message.matchId !== 0) {
      writer.uint32(16).int64(message.matchId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListenForDurableEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListenForDurableEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.matchId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListenForDurableEventRequest {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : '',
      matchId: isSet(object.matchId) ? globalThis.Number(object.matchId) : 0,
    };
  },

  toJSON(message: ListenForDurableEventRequest): unknown {
    const obj: any = {};
    if (message.taskId !== '') {
      obj.taskId = message.taskId;
    }
    if (message.matchId !== 0) {
      obj.matchId = Math.round(message.matchId);
    }
    return obj;
  },

  create(base?: DeepPartial<ListenForDurableEventRequest>): ListenForDurableEventRequest {
    return ListenForDurableEventRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListenForDurableEventRequest>): ListenForDurableEventRequest {
    const message = createBaseListenForDurableEventRequest();
    message.taskId = object.taskId ?? '';
    message.matchId = object.matchId ?? 0;
    return message;
  },
};

function createBaseDurableEvent(): DurableEvent {
  return { taskId: '', matchId: 0, data: new Uint8Array(0) };
}

export const DurableEvent: MessageFns<DurableEvent> = {
  encode(message: DurableEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== '') {
      writer.uint32(10).string(message.taskId);
    }
    if (message.matchId !== 0) {
      writer.uint32(16).int64(message.matchId);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DurableEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDurableEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.matchId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DurableEvent {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : '',
      matchId: isSet(object.matchId) ? globalThis.Number(object.matchId) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: DurableEvent): unknown {
    const obj: any = {};
    if (message.taskId !== '') {
      obj.taskId = message.taskId;
    }
    if (message.matchId !== 0) {
      obj.matchId = Math.round(message.matchId);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create(base?: DeepPartial<DurableEvent>): DurableEvent {
    return DurableEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DurableEvent>): DurableEvent {
    const message = createBaseDurableEvent();
    message.taskId = object.taskId ?? '';
    message.matchId = object.matchId ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

export type V1DispatcherDefinition = typeof V1DispatcherDefinition;
export const V1DispatcherDefinition = {
  name: 'V1Dispatcher',
  fullName: 'v1.V1Dispatcher',
  methods: {
    registerDurableEvent: {
      name: 'RegisterDurableEvent',
      requestType: RegisterDurableEventRequest,
      requestStream: false,
      responseType: RegisterDurableEventResponse,
      responseStream: false,
      options: {},
    },
    listenForDurableEvent: {
      name: 'ListenForDurableEvent',
      requestType: ListenForDurableEventRequest,
      requestStream: true,
      responseType: DurableEvent,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface V1DispatcherServiceImplementation<CallContextExt = {}> {
  registerDurableEvent(
    request: RegisterDurableEventRequest,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<RegisterDurableEventResponse>>;
  listenForDurableEvent(
    request: AsyncIterable<ListenForDurableEventRequest>,
    context: CallContext & CallContextExt
  ): ServerStreamingMethodResult<DeepPartial<DurableEvent>>;
}

export interface V1DispatcherClient<CallOptionsExt = {}> {
  registerDurableEvent(
    request: DeepPartial<RegisterDurableEventRequest>,
    options?: CallOptions & CallOptionsExt
  ): Promise<RegisterDurableEventResponse>;
  listenForDurableEvent(
    request: AsyncIterable<DeepPartial<ListenForDurableEventRequest>>,
    options?: CallOptions & CallOptionsExt
  ): AsyncIterable<DurableEvent>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString('base64');
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(''));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = {
  [Symbol.asyncIterator](): AsyncIterator<Response, void>;
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
