withTenant:
  get:
    x-resources: ["tenant"]
    description: Get all workflows for a tenant
    operationId: workflow:list
    parameters:
      - description: The tenant id
        in: path
        name: tenant
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/WorkflowList"
        description: Successfully retrieved the workflows
      "400":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: Get workflows
    tags:
      - Workflow
withWorkflow:
  get:
    x-resources: ["tenant", "workflow"]
    description: Get a workflow for a tenant
    operationId: workflow:get
    parameters:
      - description: The workflow id
        in: path
        name: workflow
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/Workflow"
        description: Successfully retrieved the workflow
      "400":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: Get workflow
    tags:
      - Workflow
workflowVersion:
  get:
    x-resources: ["tenant", "workflow"]
    description: Get a workflow version for a tenant
    operationId: workflow-version:get
    parameters:
      - description: The workflow id
        in: path
        name: workflow
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The workflow version. If not supplied, the latest version is fetched.
        in: query
        name: version
        required: false
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/WorkflowVersion"
        description: Successfully retrieved the workflow version
      "400":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
      "404":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Not found
    summary: Get workflow version
    tags:
      - Workflow
workflowVersionDefinition:
  get:
    x-resources: ["tenant", "workflow"]
    description: Get a workflow version definition for a tenant
    operationId: workflow-version:get:definition
    parameters:
      - description: The workflow id
        in: path
        name: workflow
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The workflow version. If not supplied, the latest version is fetched.
        in: query
        name: version
        required: false
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/WorkflowVersionDefinition"
        description: Successfully retrieved the workflow version definition
      "400":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
      "404":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Not found
    summary: Get workflow version definition
    tags:
      - Workflow
workflowRuns:
  get:
    x-resources: ["tenant"]
    description: Get all workflow runs for a tenant
    operationId: workflow-run:list
    parameters:
      - description: The tenant id
        in: path
        name: tenant
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The number to skip
        in: query
        name: offset
        required: false
        schema:
          type: integer
          format: int64
      - description: The number to limit by
        in: query
        name: limit
        required: false
        schema:
          type: integer
          format: int64
      - description: The event id to get runs for.
        in: query
        name: eventId
        required: false
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The workflow id to get runs for.
        in: query
        name: workflowId
        required: false
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/WorkflowRunList"
        description: Successfully retrieved the workflow runs
      "400":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: Get workflow runs
    tags:
      - Workflow
workflowRun:
  get:
    x-resources: ["tenant", "workflow-run"]
    description: Get a workflow run for a tenant
    operationId: workflow-run:get
    parameters:
      - description: The tenant id
        in: path
        name: tenant
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The workflow run id
        in: path
        name: workflow-run
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/WorkflowRun"
        description: Successfully retrieved the workflow run
      "400":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: Get workflow run
    tags:
      - Workflow
