listTasks:
  get:
    x-resources: ["tenant"]
    description: Lists all tasks for a tenant.
    operationId: v2-task:list
    parameters:
      - description: The tenant id
        in: path
        name: tenant
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The number to skip
        in: query
        name: offset
        required: false
        schema:
          type: integer
          format: int64
      - description: The number to limit by
        in: query
        name: limit
        required: false
        schema:
          type: integer
          format: int64
      - description: A list of task statuses to filter by
        in: query
        name: statuses
        required: false
        schema:
          type: array
          items:
            $ref: "../../../components/schemas/_index.yaml#/V2TaskStatus"
      - description: The earliest date to filter by
        in: query
        name: since
        required: true
        schema:
          type: string
          format: date-time
      - description: The earliest date to filter by
        in: query
        name: until
        required: false
        schema:
          type: string
          format: date-time
      - description: Additional metadata k-v pairs to filter by
        in: query
        name: additional_metadata
        required: false
        schema:
          type: array
          items:
            type: string
      - description: The workflow ids to find runs for
        in: query
        name: workflow_ids
        required: false
        schema:
          type: array
          items:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
      - description: The worker id to filter by
        in: query
        name: worker_id
        required: false
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/V2TaskSummaryList"
        description: Successfully listed the tasks
      "400":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: List tasks
    tags:
      - Task

getTask:
  get:
    x-resources: ["tenant", "task"]
    description: Get a task by id
    operationId: v2-task:get
    parameters:
      - description: The task id
        in: path
        name: task
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/V2Task"
        description: Successfully retrieved the task
      "400":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
      "404":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: The task was not found
    summary: Get a task
    tags:
      - Task

listTaskEvents:
  get:
    x-resources: ["tenant", "task"]
    description: List events for a task
    operationId: v2-task-event:list
    parameters:
      - description: The task id
        in: path
        name: task
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The number to skip
        in: query
        name: offset
        required: false
        schema:
          type: integer
          format: int64
      - description: The number to limit by
        in: query
        name: limit
        required: false
        schema:
          type: integer
          format: int64
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/V2TaskEventList"
        description: Successfully retrieved the events
      "400":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
      "404":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: The task was not found
    summary: List events for a task
    tags:
      - Task

getTaskStatusMetrics:
  get:
    x-resources: ["tenant"]
    description: Get a summary of task run metrics for a tenant
    operationId: v2-task:list:status-metrics
    parameters:
      - description: The tenant id
        in: path
        name: tenant
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The start time to get metrics for
        in: query
        name: since
        required: true
        schema:
          type: string
          format: date-time
      - description: The workflow id to find runs for
        in: query
        name: workflow_ids
        required: false
        schema:
          type: array
          items:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/V2TaskRunMetrics"
        description: Successfully retrieved the task run metrics
      "400":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: Get task metrics
    tags:
      - Task

getTaskPointMetrics:
  get:
    x-resources: ["tenant"]
    description: Get a minute by minute breakdown of task metrics for a tenant
    operationId: v2-task:get:point-metrics
    parameters:
      - description: The tenant id
        in: path
        name: tenant
        required: true
        schema:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
      - description: The time after the task was created
        in: query
        name: createdAfter
        example: "2021-01-01T00:00:00Z"
        required: false
        schema:
          type: string
          format: date-time
      - description: The time before the task was completed
        in: query
        name: finishedBefore
        example: "2021-01-01T00:00:00Z"
        required: false
        schema:
          type: string
          format: date-time
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/V2TaskPointMetrics"
        description: Successfully retrieved the task point metrics
      "400":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: A malformed or bad request
      "403":
        content:
          application/json:
            schema:
              $ref: "../../../components/schemas/_index.yaml#/APIErrors"
        description: Forbidden
    summary: Get task point metrics
    tags:
      - Task
