name: "post-user-sign-up"
version: v0.2.0
triggers:
  events:
    - user:create
jobs:
  print-user:
    steps:
      - id: echo1
        action: echo:echo
        timeout: 60s
        with:
          message: "Username is {{ .input.username }}"
      - id: echo2
        action: echo:echo
        timeout: 60s
        with:
          message: "Above message is: {{ .steps.echo1.message }}"
      - id: echo3
        action: echo:echo
        timeout: 60s
        with:
          message: "Above message is: {{ .steps.echo2.message }}"
      - id: testObject
        action: echo:object
        timeout: 60s
        with:
          object: "{{ .steps.echo3.json }}"
