// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pg_health.sql

package sqlcv1

import (
	"context"
)

const checkBloat = `-- name: CheckBloat :one
SELECT COUNT(*) FROM "Workflow" WHERE "deletedAt" IS NULL
`

func (q *Queries) CheckBloat(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, checkBloat)
	var count int64
	err := row.Scan(&count)
	return count, err
}
