require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/BlockLength:
  Max: 35
  Exclude:
    - "**/*_spec.rb"

Layout/LineLength:
  Max: 140

Style/MultilineBlockChain:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - n
    - id

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/ExampleLength:
  Max: 60

RSpec/MultipleExpectations:
  Max: 10

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false
