require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 35
  Exclude:
    - "**/*_spec.rb"

Layout/LineLength:
  Max: 140
