# frozen_string_literal: true

source "https://rubygems.org"

gem "base64"
gem "hatchet-sdk", path: "../src"

group :development do
  gem "rspec", "~> 3.0"
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
  gem "ruby-lsp", require: false
end

# HTTP for health checks in worker fixture
gem "net-http"
