# frozen_string_literal: true

source "https://rubygems.org"

gem "hatchet-sdk", path: "../src"
gem "base64"

# Testing
gem "rspec", "~> 3.0"

# HTTP for health checks in worker fixture
gem "net-http"
