# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in hatchet.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

# REST API client dependencies
gem "faraday", "~> 2.0"
gem "faraday-multipart"
gem "json", "~> 2.0"
