# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in hatchet.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.4"

gem "rspec", "~> 3.13"

gem "rubocop", "~> 1.86"

# REST API client dependencies
gem "faraday", "~> 2.0"
gem "faraday-multipart"
gem "json", "~> 2.19"
