name: "Pull Request Labeler"

on:
- pull_request_target

jobs:
  labeler:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
      with:
        sync-labels: true
