on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create prerelease w/ binaries and static assets
jobs:
  build-push-matrix:
    strategy:
      fail-fast: false
      matrix:
        target: [api, admin, engine, migrate]
        arch:
          - {tag: amd64, runner: ubuntu-latest}
          - {tag: arm64, runner: hatchet-arm64-2}
    runs-on: ${{ matrix.arch.runner }}
    name: build-push-hatchet-${{ matrix.target }}-${{ matrix.arch.tag }}
    steps:
      - name: Get tag name
        id: tag_name
        run: echo "tag=${GITHUB_TAG/refs\/tags\//}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TAG: ${{ github.ref }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./build/package/servers.dockerfile \
            --build-arg SERVER_TARGET=${{ matrix.target }} \
            --build-arg VERSION=${{ steps.tag_name.outputs.tag }} \
            -t ghcr.io/hatchet-dev/hatchet/hatchet-${{ matrix.target }}:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            --platform linux/${{ matrix.arch.tag }} \
            .
      - name: Push to GHCR
        run: docker push ghcr.io/hatchet-dev/hatchet/hatchet-${{ matrix.target }}:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }}

  build-push-frontend:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - {tag: amd64, runner: ubuntu-latest}
          - {tag: arm64, runner: hatchet-arm64-2}
    runs-on: ${{ matrix.arch.runner }}
    name: build-push-hatchet-frontend-${{ matrix.arch.tag }}
    steps:
      - name: Get tag name
        id: tag_name
        run: echo "tag=${GITHUB_TAG/refs\/tags\//}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TAG: ${{ github.ref }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
      - name: Generate docs snippets and examples
        working-directory: frontend/snippets
        run: python3 generate.py
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./build/package/frontend.dockerfile \
            -t ghcr.io/hatchet-dev/hatchet/hatchet-frontend:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            --platform linux/${{ matrix.arch.tag }} \
            .
      - name: Push to GHCR
        run: docker push ghcr.io/hatchet-dev/hatchet/hatchet-frontend:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }}

  build-push-loadtest:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - {tag: amd64, runner: ubuntu-latest}
          - {tag: arm64, runner: hatchet-arm64-2}
    runs-on: ${{ matrix.arch.runner }}
    name: build-push-hatchet-loadtest-${{ matrix.arch.tag }}
    steps:
      - name: Get tag name
        id: tag_name
        run: echo "tag=${GITHUB_TAG/refs\/tags\//}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TAG: ${{ github.ref }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./build/package/loadtest.dockerfile \
            -t ghcr.io/hatchet-dev/hatchet/hatchet-loadtest:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            --platform linux/${{ matrix.arch.tag }} \
            .
      - name: Push to GHCR
        run: docker push ghcr.io/hatchet-dev/hatchet/hatchet-loadtest:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }}

  build-push-lite:
    needs: build-push-matrix
    strategy:
      fail-fast: false
      matrix:
        arch:
          - {tag: amd64, runner: ubuntu-latest}
          - {tag: arm64, runner: hatchet-arm64-2}
    runs-on: ${{ matrix.arch.runner }}
    name: build-push-hatchet-lite-${{ matrix.arch.tag }}
    steps:
      - name: Get tag name
        id: tag_name
        run: echo "tag=${GITHUB_TAG/refs\/tags\//}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TAG: ${{ github.ref }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./build/package/servers.dockerfile \
            --build-arg SERVER_TARGET=lite \
            --build-arg VERSION=${{ steps.tag_name.outputs.tag }} \
            --platform linux/${{ matrix.arch.tag }} \
            -t hatchet-lite-tmp:${{ matrix.arch.tag }} \
            .

          DOCKER_BUILDKIT=1 docker build -f ./build/package/lite.dockerfile \
            -t ghcr.io/hatchet-dev/hatchet/hatchet-lite:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            --platform linux/${{ matrix.arch.tag }} \
            --build-arg HATCHET_LITE_IMAGE=hatchet-lite-tmp:${{ matrix.arch.tag }} \
            --build-arg HATCHET_ADMIN_IMAGE=ghcr.io/hatchet-dev/hatchet/hatchet-admin:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            --build-arg HATCHET_MIGRATE_IMAGE=ghcr.io/hatchet-dev/hatchet/hatchet-migrate:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            .
      - name: Push to GHCR
        run: docker push ghcr.io/hatchet-dev/hatchet/hatchet-lite:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }}

  build-push-dashboard:
    needs: build-push-matrix
    strategy:
      fail-fast: false
      matrix:
        arch:
          - {tag: amd64, runner: ubuntu-latest}
          - {tag: arm64, runner: hatchet-arm64-2}
    runs-on: ${{ matrix.arch.runner }}
    name: build-push-hatchet-dashboard-${{ matrix.arch.tag }}
    steps:
      - name: Get tag name
        id: tag_name
        run: echo "tag=${GITHUB_TAG/refs\/tags\//}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TAG: ${{ github.ref }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./build/package/dashboard.dockerfile \
            -t ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            --platform linux/${{ matrix.arch.tag }} \
            --build-arg HATCHET_API_IMAGE=ghcr.io/hatchet-dev/hatchet/hatchet-api:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }} \
            .
      - name: Push to GHCR
        run: docker push ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:${{ steps.tag_name.outputs.tag }}-${{ matrix.arch.tag }}

  combine:
    needs: [build-push-matrix, build-push-frontend, build-push-loadtest, build-push-lite, build-push-dashboard]
    strategy:
      fail-fast: false
      matrix:
        target: [api, admin, engine, migrate, frontend, loadtest, lite, dashboard]
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tag_name
        run: echo "tag=${GITHUB_TAG/refs\/tags\//}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TAG: ${{ github.ref }}
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Combine
        env:
          IMAGE: ghcr.io/hatchet-dev/hatchet/hatchet-${{ matrix.target }}:${{ steps.tag_name.outputs.tag }}
        run: |
          docker manifest create $IMAGE $IMAGE-amd64 $IMAGE-arm64
          docker manifest push $IMAGE
