name: typescript-manual-publish
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./sdks/typescript

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install pnpm
        run: npm install -g pnpm@10.16.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build and Publish SDK
        run: |
          VERSION=$(jq '.version' package.json)

          ## If the version contains `alpha`, it's an alpha version
          ## and we should tag it as such.=
          if [[ "$VERSION" == *alpha* ]]; then
              pnpm publish:ci:alpha
          else
              pnpm publish:ci
          fi
          echo "VERSION_TAG=$NEW_VERSION" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Generate release notes"
        if: env.VERSION_TAG != ''
        working-directory: ${{ github.workspace }}
        run: ./hack/ci/release-notes.sh typescript > ./release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Release"
        if: env.VERSION_TAG != ''
        working-directory: ${{ github.workspace }}
        run: |
          gh release create "ts/${VERSION_TAG}" \
            --target "$GITHUB_SHA" \
            --title "Typescript SDK ${VERSION_TAG}" \
            --notes-file ./release_notes.md \
            --latest=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
