name: python / old-engine-new-sdk
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./sdks/python

jobs:
  old-engine-new-sdk:
    runs-on: ubicloud-standard-4
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Start Hatchet embedded (released sidecar)
        uses: ./.github/actions/hatchet-embedded-release
        with:
          log-file: engine.log

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
        with:
          version: 2.3.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --all-extras

      - name: Set HATCHET_CLIENT_NAMESPACE
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "HATCHET_CLIENT_NAMESPACE=old-engine-new-sdk-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Run pytest
        id: run-tests
        continue-on-error: true
        env:
          HATCHET_CLIENT_TLS_STRATEGY: none
          HATCHET_CLIENT_WORKER_HEALTHCHECK_ENABLED: "True"
        run: |
          echo "Testing current SDK against engine ${{ env.HATCHET_ENGINE_VERSION }}"
          echo "Using HATCHET_CLIENT_NAMESPACE: $HATCHET_CLIENT_NAMESPACE"
          poetry run pytest -s -vvv --maxfail=5 --capture=no --retries 3 --retry-delay 2 -n auto

      - name: Upload engine logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.HATCHET_CLIENT_NAMESPACE }}-engine-logs
          path: engine.log
