name: spelling
on: pull_request
jobs:
      spelling:
            runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
                  - uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
                    continue-on-error: true
