name: 'Close stale issues'
on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  actions: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          stale-issue-message: 'This issue has been stale for 90 days. Please update the issue or comment to keep it active. Otherwise, it will be closed in 5 days.'
          days-before-stale: 90
          days-before-close: 5
          stale-issue-label: 'stale'
          exempt-issue-labels: 'accepted'
