name: 'Close stale issues'
on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  actions: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-issue-message: 'This issue has been stale for 90 days. Please update the issue or comment to keep it active. Otherwise, it will be closed in 5 days.'
          days-before-stale: 90
          days-before-close: 5
          stale-issue-label: 'stale'
          exempt-issue-labels: 'accepted'
